name: Emacs 26

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'Formula/emacs-head@26.rb'
      - 'patches/**'
      - 'Library/**'
      - '.github/workflows/emacs-26.yml'
  pull_request:
    paths:
      - 'Formula/emacs-head@26.rb'
      - 'patches/**'
      - 'Library/**'
      - '.github/workflows/emacs-26.yml'
  schedule:
    - cron:  '0 7 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]
        build_opts:
          # All options (imagemagick@6)
          - '--with-cocoa --with-no-frame-refocus --with-imagemagick --with-multicolor-fonts --with-retro-icon-sink-bw'

    env:
      HOMEBREW_EMACS_HEAD_GITHUB_REPOSITORY: ${{ github.repository }}
      HOMEBREW_EMACS_HEAD_GITHUB_REPOSITORY_REF: ${{ github.head_ref || github.ref }}

    steps:
    - uses: actions/checkout@v5

    - name: Tap emacs-head
      run: |
        brew tap daviderestivo/emacs-head

    - name: Build emacs-head@26 ${{ matrix.build_opts }}
      run: |
        brew update
        brew upgrade || true
        # Remove Homebrew cache locks
        rm -rf ~/Library/Caches/Homebrew/locks
        brew install --verbose emacs-head@26 ${{ matrix.build_opts }}
      working-directory: Formula

    - name: Test installation
      run: $(brew --prefix)/bin/emacs --batch --eval='(print (+ 2 2))'
      working-directory: Formula
