name: Emacs 29

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'Formula/emacs-head@29.rb'
      - 'patches/**'
      - '.github/workflows/emacs-29.yml'
  pull_request:
    paths:
      - 'Formula/emacs-head@29.rb'
      - 'patches/**'
      - '.github/workflows/emacs-29.yml'
  schedule:
    - cron:  '0 7 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11]
        build_opts:
          # All options (imagemagick@7)
          - '--with-cocoa --with-no-frame-refocus --with-imagemagick --with-pdumper --with-xwidgets'
          # All options (imagemagick@7) + native-comp support
          - '--with-cocoa --with-no-frame-refocus --with-imagemagick --with-pdumper --with-xwidgets --with-native-comp'

    env:
      HOMEBREW_GITHUB_REF: ${{ github.head_ref || github.ref }}
      HOMEBREW_GITHUB_REPOSITORY: ${{ github.repository }}
      HOMEBREW_GITHUB_ACTOR: ${{ github.actor }}

    steps:
    - uses: actions/checkout@v2.3.5

    - name: Use XCode 12.5 for Big Sur
      if: contains(matrix.os, 'macos-11')
      run: sudo xcode-select -s "/Applications/Xcode_12.5.app"

    - name: Build emacs-head@29 ${{ matrix.build_opts }}
      run: brew install --verbose emacs-head@29.rb ${{ matrix.build_opts }}
      working-directory: Formula

    - name: Test installation
      run: brew test emacs-head@29.rb
      working-directory: Formula
